ahrm/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^ahrm/', include('ahrm.foo.urls')),

    (r'^', include('ahrm.main.urls')),
    (r'^system/help$', 'main.views.help'),
    #static content path (js, css...)
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root':settings.MEDIA_ROOT}),
                      
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^i18n/', include('django.conf.urls.i18n')),

)

ahrm/main/models.py
################################################################### #
# Project:    A*HRM                                                 #
# Title:     Class Models of A*HRM Database (PostgrSQL)             #  
# Version:     0001                                                 #
# Last-Modified:     2009-02-26 05:36:39  (Thu, 26 Feb 2009)        #
# Author:     Sokha, Sin , Sanya, Mesa ,Kanel (ALLWEB DEVELOPERS)   #
# Status:     Active                                                #
# Type:     Process                                                 #
# Created:     20-Feb-2009                                          #
# Post-History:     03-Feb-2009                                     #
#####################################################################

from django.db import models
from django.contrib.auth.models import User
from django import forms as forms
from django.forms.widgets import *
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import datetime, time
from tinymce import models as tinymce_models
from django.utils.translation import ugettext_lazy



class Country(models.Model):
    code = models.CharField(max_length=3)
    name = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    def __unicode__(self):
        return self.name
   
class Gender(models.Model):
    code = models.CharField(max_length=1, primary_key=True)
    desc = models.CharField(max_length=10)
    def __unicode__(self):
        return self.desc

class Company(models.Model):
    desc = models.CharField(ugettext_lazy('Description'),max_length=255)
    name = models.CharField(ugettext_lazy('Name'),max_length=40, )
    address = models.CharField(ugettext_lazy('Address'),max_length=500)
    city = models.CharField(ugettext_lazy('City'),max_length=100, blank=True, null=True)
    zipcode = models.CharField(ugettext_lazy('Zip code'),max_length=5, blank=True, null=True)
    phone1 = models.CharField(ugettext_lazy('Phone1'),max_length=20, blank=True, null=True)
    phone2 = models.CharField(ugettext_lazy('Phone2'),max_length=20, blank=True, null=True)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=40, blank=True, null=True)
    welcome_message = tinymce_models.HTMLField(blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name=ugettext_lazy('Country'))
    logo = models.ImageField(upload_to="images/company_logo/", blank=True, help_text="Should be 50px wide")
    banner = models.ImageField(upload_to="images/company_banner/", blank=True, null=True)
    def __unicode__(self):
        return self.name
    
    def get_name(self):
        return self.name

class UserCompany(models.Model):
    company = models.ForeignKey(Company)
    user = models.ForeignKey(User)
    
class ModelType(models.Model):
    type_code = models.CharField(max_length=50, primary_key=True)
    type_desc = models.CharField(max_length=100)
    def __unicode__(self):
        return self.type_desc
        
class Department(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=50)
    desc = models.CharField(ugettext_lazy('Description'),max_length=200)    
    department_father = models.ForeignKey('self', blank=True, null=True)
    company = models.ForeignKey(Company)
    type = models.ForeignKey(ModelType)
    order_id = models.IntegerField()
    def __unicode__(self):        
        return "%s (%s)" % (self.name, self.company)
        

#This indicate the marital status   
class MaritalStatus(models.Model):
    code = models.CharField(max_length=5)
    desc = models.TextField(ugettext_lazy('Description'),max_length=200)    
    def __unicode__(self):        
        return self.desc
    

class Employee(models.Model):
    lname = models.CharField(ugettext_lazy('Last name'),max_length=200)    
    fname = models.CharField(ugettext_lazy('First name'),max_length=200)
    birthday = models.DateField(ugettext_lazy('Birthday'))
    marital_status = models.ForeignKey(MaritalStatus, verbose_name=ugettext_lazy('Marital Status'))
    driver_licence = models.CharField(ugettext_lazy('Driver licence'),max_length=50, blank=True, null=True)
    street = models.CharField(ugettext_lazy('Street'),max_length=50, blank=True, null=True)
    city = models.CharField(ugettext_lazy('City'),max_length=100)
    zip_code = models.CharField(ugettext_lazy('Zip code'),max_length=5)
    phone = models.CharField(ugettext_lazy('Phone'),max_length=20, blank=True)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=40, blank=True)
    date_joined = models.DateField(ugettext_lazy('Date joined'))
    photo = models.ImageField(upload_to="images/photo/", blank=True, help_text="Should be 50px wide")
    active = models.BooleanField(ugettext_lazy('Active'))
    nationality = models.ForeignKey(Country)
    gender = models.ForeignKey(Gender, verbose_name=ugettext_lazy('Gender'))
    #department = models.ForeignKey(Department, blank=True, null=True)
    company = models.ForeignKey(Company, blank=False, null=False)
    def __unicode__(self):
        return "%s (%s)" % (self.lname, self.fname)
    def get_fullname(self):
       
        return ('%s %s' % (self.fname.upper(),self.lname))        
    get_fullname.short_description = 'Fullname'
    
    def photo_thumb(self):
        if self.photo:
            return '<img src="/%s/%s"></a>' % (settings.MEDIA_ROOT,self.photo)
        return None
    
    def get_age(self):
        current_date = time.localtime()
        birth_date = self.birthday.timetuple()
        
        d_year = current_date[0] - birth_date[0]
        d_month = current_date[1] - birth_date[1]
        d_day = current_date[2] - birth_date[2]
        
        if d_day <0:
            d_day = d_day + 30
            d_month = d_month-1
        #checks if difference in month is negative when difference in day is positive
        if d_month < 0 :
            d_month = d_month + 12
            d_year =  d_year - 1
        #the age found is:  d_year years and d_month months and d_day days
        return d_year
    def first_department_position(self):
        emp_pos = EmployeePosition.objects.filter(employee=self.id)
        if len(emp_pos) >0 :
            return emp_pos[0] 
        else :
            return ""
    photo_thumb.allow_tags = True
    photo_thumb.short_description = 'photo(95px*130px)'
   

class Emergency(models.Model):
    lname = models.CharField(ugettext_lazy('Last name'),max_length=100)    
    fname = models.CharField(ugettext_lazy('First name'),max_length=100)
    phone = models.CharField(ugettext_lazy('Phone'),max_length=50)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=50)
    relationship = models.CharField(ugettext_lazy('Relationship'),max_length=50)
    employee = models.ForeignKey(Employee)#A employee has many Emergencies
    
class Experience(models.Model):
    start_date = models.CharField(ugettext_lazy('Start date'),max_length=100,blank=True, null=True)
    end_date = models.CharField(ugettext_lazy('End date'),max_length=100,blank=True, null=True)
    position = models.CharField(ugettext_lazy('Position'),max_length=100, blank=False, null=False)
    mission = models.TextField(ugettext_lazy('Mission'),max_length=1000)
    location = models.CharField(ugettext_lazy('Location'),max_length=100)
    employee = models.ForeignKey(Employee)
    
class Education(models.Model):
    school = models.CharField(ugettext_lazy('School'),max_length=100)
    start_date = models.CharField(ugettext_lazy('End date'),max_length=100,blank=True, null=True)
    end_date = models.CharField(ugettext_lazy('Start date'),max_length=100,blank=True, null=True)
    specialist = models.CharField(ugettext_lazy('Specialist'),max_length=100)
    employee = models.ForeignKey(Employee)
    description = models.TextField(ugettext_lazy('Description'),max_length=1000)

class Skill(models.Model):
    skill_name = models.CharField(ugettext_lazy('Skill'),max_length=100)
    description = models.TextField(max_length=1000, blank=True, null=True)
    employee = models.ForeignKey(Employee)
    
class EmployeeLanguage(models.Model):
    employee = models.ForeignKey(Employee)
    language = models.ForeignKey(Country, verbose_name=ugettext_lazy('Language'))
    COMPETENCY_CHOICES = (('Poor', 'Poor'), ('Basic', 'Basic'), ('Good', 'Good'), ('Mother tongue', 'Mother tongue'))
    FLUENCY_CHOICES = (('Writing' ,'Writing'),('Speaking', 'Speaking'), ('Reading', 'Reading'))
    competency = models.CharField(ugettext_lazy('Competency'),max_length=1, choices=COMPETENCY_CHOICES)
    fluency = models.CharField(ugettext_lazy('Fluency'),max_length=1, choices=FLUENCY_CHOICES)
    def __unicode__(self):
        return self.language


class Position(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=100)
    description = models.CharField(ugettext_lazy('Description'),max_length=500)
    company = models.ForeignKey(Company, blank=False, null=False)
    def __unicode__(self):
        return self.name


class EmployeePosition(models.Model):
    employee = models.ForeignKey(Employee)
    position = models.ForeignKey(Position)
    department = models.ForeignKey(Department, blank=True, null=True)
    def __unicode__(self):
        return str(self.position) + ' - ' + str(self.department) 

class Attachment(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=50)
    description = models.CharField(ugettext_lazy('Description'),max_length=100)
    extension = models.CharField(max_length=10,blank=True, null=True)
    size = models.FloatField(blank=True, null=True)
    content = models.FileField(ugettext_lazy('Content'),upload_to='attachments')
    employee = models.ForeignKey(Employee)
    def get_file_name(self):
        return str(self.content)[len('attachments')+1:]
    
    def get_extension(self):
        str_content=str(self.content)
        return str_content[str_content.find('.'):]

ahrm/templates/companies/companies_show_list.html
{% extends "master.html" %}
{% load ahrm_tags %}

{% block title %}AHRM - Companies List{% endblock %}

{% block content %}
{% load i18n %}
<script type="text/javascript" language="JavaScript">
    function before_delete(com_name) {
        if (confirm('{% trans 'Do you want to delete company' %} ' + com_name + '{% trans ' ?' %}')) {
            return true;
        }
        return false;
    }
</script>
<br/>
{% ifequal process 0 %}
    <h4>{% trans 'Select one of the following company to enter' %}:</h4>
{% else %}
    <h4>{% trans 'Select one of the following company to see detail' %}:</h4>
{% endifequal %}

<table class="ahrmtablelist" border="1">
                    <thead>
                        <th>{% trans 'Id' %}</th>
                        <th>{% trans 'Name' %}</th>
                        <th>{% trans 'Description' %}</th>
                        <th>{% trans 'Phone' %}</th>
                        <th>{% trans 'Address' %}</th>
                        {% ifequal process 1 %}
                        <th>{% trans 'Delete' %}</th>
                        {% endifequal %}
                    </thead>
                {% if company_list %}
                    {% for company in company_list %}
                        <tr>
                            <td class="left">{{ company.id }}</td>
                            <td>
                                {% ifequal process 0 %}
                                    <a href = "/company/enter/{{ company.id }}">
                                {% else %}
                                    <a href = "/company/edit/{{ company.id }}">
                                {% endifequal %}
                                   {{ company.name }}
                                </a>
                            </td>
                            <td>{{ company.desc }}</td>
                            <td>{{ company.phone1 }}</td>
                            <td>{{ company.city }}</td>
                            {% ifequal process 1 %}
                                {%ifnotequal company.id com_id%}
                                   <td align="center"><a title="Delete company {{company.name}}" href="/company/delete/{{company.id}}" onclick="return before_delete('{{ company.name }}')"><img src="/site_media/images/delete.gif" border="0"></a></td>
                                {%endifnotequal%}
                            {% endifequal %}
                        </tr>   
                    {% endfor %}
                {% else %}
                    <font color = "red"> <br>{% trans 'There no company recorded in the company list.' %}</font>
                {% endif %}
            </table>
            <br/>
                <form method="post">
                {% ifnotequal user_type 2%}
	                {% ifequal process 1 %}
	                   <input type="button" onclick="process('/company/new')" value="{% trans 'New Company' %}"/>
	                {% else %}
	                    {% ifequal user_type 0 %}
	                       <input type="button" onclick="process('/company/initialize')" value="{% trans 'New Company' %}"/>
	                    {% endifequal %}
	                {% endifequal %}
	            {% endifnotequal %}
                <form>
            
            
            
            <br/><br/>
            
{% endblock %}

ahrm/templates/companies/company_edit.html
{% extends "master.html" %}
{% load ahrm_tags %}
{% load i18n %}
{% block title %}AHRM - Compamy{% endblock %}

{% block content %}

{{form.media}}

<h2>&nbsp;</h2>
<form method="POST" enctype="multipart/form-data">
  <font color="red"><b>
  {% if error_name %}
     <label for="id_name">{% trans 'Name' %}</label>: {% trans 'This field is required.' %}<br/>
  {% endif %}
  {% if form.errors %}
     
     {% for field in form %}
        {% if field.errors %}
           {% for error in  field.errors %}
            {{ field.label_tag }}: {{ error }}<br/>
           {% endfor %}
        {% endif %}
     {% endfor %}
  {% endif %}
  </b></font>
  
  <table class="ahrmtable" border=0>
    <thead>
       <th colspan="6" align="left">{% trans 'Company detail' %}</th>
    </thead>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td colspan="2">&nbsp;</td>
     </tr>
     <tr>
        <td>{% trans 'Name' %}: </td>
        <td>
        {% if com_id %}
           {{com_name}}<input type="hidden" value="{{com_name}}" name="id_name"/>
        {% else %}
           <input type="text" value="{{com_name}}" name="id_name" id="id_name"/>
        {% endif %}
        
        </td>
        <td>{% trans 'Description' %}: </td>
        <td>{{form.desc}}</td>
        <td rowspan="4">
        	{% if not company_logo %}
        		<img src="/site_media/images/bg.jpg" style="width: 3cm;height: 3cm; border: solid 1px"/>
        	{% else %}
        		<img src="/site_media/{{company_logo}}" style="width: 3cm;height: 3cm; border: solid 1px"/>
        	{% endif %}
        	
        </td>
     </tr>
     <tr>
        <td>{% trans 'Address' %}: </td>
        <td>{{form.address}}</td>
        <td>{% trans 'City' %}: </td>
        <td>{{form.city}}</td>
        <td>&nbsp;</td>
     </tr>
     <tr>
        <td>{% trans 'E-mail' %}: </td>
        <td>{{form.mail}}</td>
        <td>{% trans 'Zip Code' %}: </td>
        <td>{{form.zipcode}}</td>
        <td>&nbsp;</td>
     </tr>
     <tr>
        <td>{% trans 'Tel' %}.1: </td>
        <td>{{form.phone1}}</td>
        <td>{% trans 'Tel' %}.2: </td>
        <td>{{form.phone2}}</td>
        <td>&nbsp;</td>
     </tr>
     <tr>
        <td>{% trans 'Country' %}: </td>
        <td>{{form.country}}</td>
        <td>{% trans 'Company logo' %}:</td>
        <td colspan="2">{{form.logo}}</td>
     </tr>
     <tr>
        <td>{% trans 'Company banner' %}:</td>
        <td>{{form.banner}}</td>
        <td colspan="3">&nbsp;</td>
     </tr>
     <tr>
        <td valign="top">{% trans 'Welcome Message' %}: </td>
        <td colspan="4">{{form.welcome_message}}</td>
     </tr>
     <tr>
        <td colspan="5">&nbsp;</td>
     </tr>
  </table>
  <br/>
  
  <input type="submit" value="{% trans 'Save' %}" name="com_edit_save" />
  {% if not initialize %} 
      &nbsp;&nbsp;<input type="button" value="{% trans 'Back' %}" onclick="process('/companies/list')" />
  {% else %}
      &nbsp;&nbsp;<input type="button" value="{% trans 'Back' %}" onclick="process('/companies/show')" />
  {% endif %}
  <input type="hidden" value="{{com_id}}" name="com_id"/>
  <br/><br/>
</form>
{% endblock %}