ahrm/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^ahrm/', include('ahrm.foo.urls')),

    (r'^', include('ahrm.main.urls')),
    (r'^system/help$', 'main.views.help'),
    #static content path (js, css...)
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root':settings.MEDIA_ROOT}),
                      
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^i18n/', include('django.conf.urls.i18n')),

)

ahrm/main/models.py
################################################################### #
# Project:    A*HRM                                                 #
# Title:     Class Models of A*HRM Database (PostgrSQL)             #  
# Version:     0001                                                 #
# Last-Modified:     2009-02-26 05:36:39  (Thu, 26 Feb 2009)        #
# Author:     Sokha, Sin , Sanya, Mesa ,Kanel (ALLWEB DEVELOPERS)   #
# Status:     Active                                                #
# Type:     Process                                                 #
# Created:     20-Feb-2009                                          #
# Post-History:     03-Feb-2009                                     #
#####################################################################

from django.db import models
from django.contrib.auth.models import User
from django import forms as forms
from django.forms.widgets import *
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import datetime, time
from tinymce import models as tinymce_models
from django.utils.translation import ugettext_lazy



class Country(models.Model):
    code = models.CharField(max_length=3)
    name = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    def __unicode__(self):
        return self.name
   
class Gender(models.Model):
    code = models.CharField(max_length=1, primary_key=True)
    desc = models.CharField(max_length=10)
    def __unicode__(self):
        return self.desc

class Company(models.Model):
    desc = models.CharField(ugettext_lazy('Description'),max_length=255)
    name = models.CharField(ugettext_lazy('Name'),max_length=40, )
    address = models.CharField(ugettext_lazy('Address'),max_length=500)
    city = models.CharField(ugettext_lazy('City'),max_length=100, blank=True, null=True)
    zipcode = models.CharField(ugettext_lazy('Zip code'),max_length=5, blank=True, null=True)
    phone1 = models.CharField(ugettext_lazy('Phone1'),max_length=20, blank=True, null=True)
    phone2 = models.CharField(ugettext_lazy('Phone2'),max_length=20, blank=True, null=True)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=40, blank=True, null=True)
    welcome_message = tinymce_models.HTMLField(blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name=ugettext_lazy('Country'))
    logo = models.ImageField(upload_to="images/company_logo/", blank=True, help_text="Should be 50px wide")
    banner = models.ImageField(upload_to="images/company_banner/", blank=True, null=True)
    def __unicode__(self):
        return self.name
    
    def get_name(self):
        return self.name

class UserCompany(models.Model):
    company = models.ForeignKey(Company)
    user = models.ForeignKey(User)
    
class ModelType(models.Model):
    type_code = models.CharField(max_length=50, primary_key=True)
    type_desc = models.CharField(max_length=100)
    def __unicode__(self):
        return self.type_desc
        
class Department(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=50)
    desc = models.CharField(ugettext_lazy('Description'),max_length=200)    
    department_father = models.ForeignKey('self', blank=True, null=True)
    company = models.ForeignKey(Company)
    type = models.ForeignKey(ModelType)
    order_id = models.IntegerField()
    def __unicode__(self):        
        return "%s (%s)" % (self.name, self.company)
        

#This indicate the marital status   
class MaritalStatus(models.Model):
    code = models.CharField(max_length=5)
    desc = models.TextField(ugettext_lazy('Description'),max_length=200)    
    def __unicode__(self):        
        return self.desc
    

class Employee(models.Model):
    lname = models.CharField(ugettext_lazy('Last name'),max_length=200)    
    fname = models.CharField(ugettext_lazy('First name'),max_length=200)
    birthday = models.DateField(ugettext_lazy('Birthday'))
    marital_status = models.ForeignKey(MaritalStatus, verbose_name=ugettext_lazy('Marital Status'))
    driver_licence = models.CharField(ugettext_lazy('Driver licence'),max_length=50, blank=True, null=True)
    street = models.CharField(ugettext_lazy('Street'),max_length=50, blank=True, null=True)
    city = models.CharField(ugettext_lazy('City'),max_length=100)
    zip_code = models.CharField(ugettext_lazy('Zip code'),max_length=5)
    phone = models.CharField(ugettext_lazy('Phone'),max_length=20, blank=True)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=40, blank=True)
    date_joined = models.DateField(ugettext_lazy('Date joined'))
    photo = models.ImageField(upload_to="images/photo/", blank=True, help_text="Should be 50px wide")
    active = models.BooleanField(ugettext_lazy('Active'))
    nationality = models.ForeignKey(Country)
    gender = models.ForeignKey(Gender, verbose_name=ugettext_lazy('Gender'))
    #department = models.ForeignKey(Department, blank=True, null=True)
    company = models.ForeignKey(Company, blank=False, null=False)
    def __unicode__(self):
        return "%s (%s)" % (self.lname, self.fname)
    def get_fullname(self):
       
        return ('%s %s' % (self.fname.upper(),self.lname))        
    get_fullname.short_description = 'Fullname'
    
    def photo_thumb(self):
        if self.photo:
            return '<img src="/%s/%s"></a>' % (settings.MEDIA_ROOT,self.photo)
        return None
    
    def get_age(self):
        current_date = time.localtime()
        birth_date = self.birthday.timetuple()
        
        d_year = current_date[0] - birth_date[0]
        d_month = current_date[1] - birth_date[1]
        d_day = current_date[2] - birth_date[2]
        
        if d_day <0:
            d_day = d_day + 30
            d_month = d_month-1
        #checks if difference in month is negative when difference in day is positive
        if d_month < 0 :
            d_month = d_month + 12
            d_year =  d_year - 1
        #the age found is:  d_year years and d_month months and d_day days
        return d_year
    def first_department_position(self):
        emp_pos = EmployeePosition.objects.filter(employee=self.id)
        if len(emp_pos) >0 :
            return emp_pos[0] 
        else :
            return ""
    photo_thumb.allow_tags = True
    photo_thumb.short_description = 'photo(95px*130px)'
   

class Emergency(models.Model):
    lname = models.CharField(ugettext_lazy('Last name'),max_length=100)    
    fname = models.CharField(ugettext_lazy('First name'),max_length=100)
    phone = models.CharField(ugettext_lazy('Phone'),max_length=50)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=50)
    relationship = models.CharField(ugettext_lazy('Relationship'),max_length=50)
    employee = models.ForeignKey(Employee)#A employee has many Emergencies
    
class Experience(models.Model):
    start_date = models.CharField(ugettext_lazy('Start date'),max_length=100,blank=True, null=True)
    end_date = models.CharField(ugettext_lazy('End date'),max_length=100,blank=True, null=True)
    position = models.CharField(ugettext_lazy('Position'),max_length=100, blank=False, null=False)
    mission = models.TextField(ugettext_lazy('Mission'),max_length=1000)
    location = models.CharField(ugettext_lazy('Location'),max_length=100)
    employee = models.ForeignKey(Employee)
    
class Education(models.Model):
    school = models.CharField(ugettext_lazy('School'),max_length=100)
    start_date = models.CharField(ugettext_lazy('End date'),max_length=100,blank=True, null=True)
    end_date = models.CharField(ugettext_lazy('Start date'),max_length=100,blank=True, null=True)
    specialist = models.CharField(ugettext_lazy('Specialist'),max_length=100)
    employee = models.ForeignKey(Employee)
    description = models.TextField(ugettext_lazy('Description'),max_length=1000)

class Skill(models.Model):
    skill_name = models.CharField(ugettext_lazy('Skill'),max_length=100)
    description = models.TextField(max_length=1000, blank=True, null=True)
    employee = models.ForeignKey(Employee)
    
class EmployeeLanguage(models.Model):
    employee = models.ForeignKey(Employee)
    language = models.ForeignKey(Country, verbose_name=ugettext_lazy('Language'))
    COMPETENCY_CHOICES = (('Poor', 'Poor'), ('Basic', 'Basic'), ('Good', 'Good'), ('Mother tongue', 'Mother tongue'))
    FLUENCY_CHOICES = (('Writing' ,'Writing'),('Speaking', 'Speaking'), ('Reading', 'Reading'))
    competency = models.CharField(ugettext_lazy('Competency'),max_length=1, choices=COMPETENCY_CHOICES)
    fluency = models.CharField(ugettext_lazy('Fluency'),max_length=1, choices=FLUENCY_CHOICES)
    def __unicode__(self):
        return self.language


class Position(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=100)
    description = models.CharField(ugettext_lazy('Description'),max_length=500)
    company = models.ForeignKey(Company, blank=False, null=False)
    def __unicode__(self):
        return self.name


class EmployeePosition(models.Model):
    employee = models.ForeignKey(Employee)
    position = models.ForeignKey(Position)
    department = models.ForeignKey(Department, blank=True, null=True)
    def __unicode__(self):
        return str(self.position) + ' - ' + str(self.department) 

class Attachment(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=50)
    description = models.CharField(ugettext_lazy('Description'),max_length=100)
    extension = models.CharField(max_length=10,blank=True, null=True)
    size = models.FloatField(blank=True, null=True)
    content = models.FileField(ugettext_lazy('Content'),upload_to='attachments')
    employee = models.ForeignKey(Employee)
    def get_file_name(self):
        return str(self.content)[len('attachments')+1:]
    
    def get_extension(self):
        str_content=str(self.content)
        return str_content[str_content.find('.'):]

ahrm/templates/reports/employee_report_pdf.html
<! DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN " 
"http://www.w3.org/TR/html4/loose.dtd">
{% load i18n %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style>
   .block_header {
       font: bold 20px oblique;
       color: black;
       text-decoration: underline;
   }
   
   
   @font-face {
        font-family: "CODE2000";
        src: url("{{url}}/font/code2000.ttf")
    }

    html {
        font-family: "code2000";
    }
   
</style>

</head>
<body>
<div id="headerContent" align="right">
<img src="{{ url }}/{{ curr_employee.company.logo }}" width="4cm" height="4cm" align="left"/>
ALLWEB Human Resource Management
  <hr/>
</div>

<h1 class="block_header">{% trans 'Personal Information' %} </h1>
<table border="0">
<tr>
    <td valign="top" width="80%">
        <table width="100%">
           <tr>
                <td width="20%"><span class="name">{% trans 'Name' %}</span></td>
                <td>: <b>{{ curr_employee.fname }} {{ curr_employee.lname }}</b></td>
           </tr>
           <tr>
                <td>{% trans 'Age' %}</td>
                <td>: <b>{{ curr_employee.get_age }}</b></td>
           </tr>
           <tr>
                <td>{% trans 'Nationality' %}</td>
                <td>: <b>{{ curr_employee.nationality.nationality }}</b></td>
           </tr>
           <tr>
               <td valign="top">{% trans 'Address' %}</td>
               <td>: <b>{{ curr_employee.street }} {{ curr_employee.city }}</b></td>
          </tr>
         <tr>
               <td>{% trans 'Phone' %}</td>
               <td>: <b>{{ curr_employee.phone }}</b></td>
          </tr>
          <tr>
               <td>{% trans 'E-mail' %}</td>
               <td>: <b>{{ curr_employee.mail }}</b></td>
          </tr>           
      </table>         
    </td>
    <td valign="top" align="right">
        &nbsp;<img src="{{ url }}/{{ curr_employee.photo }}" width="3cm" height="4cm" />
    </td>
</tr>
</table>

{% if curr_employee.education_set.all %}
<br/>
<h1 class="block_header">{% trans 'Education' %}</h1>
{% for education in curr_employee.education_set.all %}
<table width="100%" repeat="1">
    <tr>
         <td>{{education.start_date}} - {{education.end_date}}</td>
    </tr>
    <tr>
         <td>{{education.school}}</td>
    </tr>
    <tr>
         <td>{{education.specialist}}</td>
    </tr>
</table>
{% endfor %}
{% endif %}


{% if curr_employee.experience_set.all %}
<br/>
<h1 class="block_header" repeat="1">{% trans 'Experience' %}</h1><br/>
{% for experience in curr_employee.experience_set.all %}
<table width="100%" repeat="1">
    <tr>
         <td style="font: bold">{{experience.start_date}} - {{experience.end_date}}</td>
         <td colspan="2">{{ experience.location }}</td>
    </tr>
    <tr>
       <td width="20%">&nbsp;</td>
       <td width="15%">{% trans 'Position' %} : </td>
       <td>{{ experience.position }}</td>
    </tr>
    <tr valign="top">
       <td>&nbsp;</td>
       <td>{% trans 'Mission' %}:</td>
       <td> <b>{{ experience.mission }}</b></td>
    </tr>
</table>

{% endfor %}
{% endif %}

{% if curr_employee.skill_set.all %}
<br/>
<h1 class="block_header" repeat="1">{% trans 'Skill'%}</h1><br/>
<table width="100%"  repeat="1">
{% for skill in curr_employee.skill_set.all %}
    <tr valign="top">
         <td width="15%">{{skill.skill_name}} : </td>
         <td>{{skill.description }}</td>
    </tr>
{% endfor %}
</table>
{% endif %}

{% if curr_employee.employeelanguage_set.all %}
<br/>
<h1 class="block_header">{% trans 'Language' %}</h1><br/>
<table width="100%" repeat="1">
{% for emp_lang in curr_employee.employeelanguage_set.all %}
    <tr>
        <td  width="20%">{{emp_lang.language.language}} : </td>
        <td>{{emp_lang.competency}}</td>
    </tr>
{% endfor %}
</table>
{% endif %}
<div id="footerContent" align="center">
  <hr/><br/>
  {{ curr_employee.company.address }}
  </div>
</body>
</html>

ahrm/templates/reports/employees_contacts_list.html
<! DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN " 
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" media="screen" href="/site_media/style.css" />
<style>
   .block_header {
       font: bold 20px oblique;
       color: black;
       text-decoration: underline;
   }
   
   @font-face {
        font-family: "CODE2000";
        src: url("{{url}}/font/code2000.ttf")
    }

    html {
        font-family: "code2000";
    }

</style>

</head>
<body>

<div id="headerContent" align="right">
   <img src="{{ url }}/{{company.logo}}" width="4cm" height="4cm" align="left"/>{{company.name}} Human Resource Management
  <hr/>
</div>
{% load i18n %}
<h1>{% trans 'Contacts List' %} </h1>
<table border="1" class="ahrmtablelist">
	<thead>
	    <th align="center"><br>{% trans 'Nº' %}</th>
	    <th align="center">{% trans 'First Name' %}</td>
	    <th align="center">{% trans 'Last Name' %}</td>
	    <th align="center">{% trans 'Telephone' %}</td>
	    <th align="center">{% trans 'E-mail' %}</td>	    
	</thead>
	{% for employee in employees %}
		<tr>
			<td  align="center"><br>{{forloop.counter}}</td>
			<td>&nbsp{{employee.fname}}</td>
			<td>&nbsp{{employee.lname}}</td>
			<td>&nbsp{{employee.phone}}</td>
			<td>&nbsp{{employee.mail}}</td>
		</tr>
	{% endfor %}
</table>
<!-- Here is footer -->
<div id="footerContent" align="center">
  <hr/><br/>
  {{company.name}} Company<br/>{{company.address}}.
 </div>
</body>
</html>