ahrm/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^ahrm/', include('ahrm.foo.urls')),

    (r'^', include('ahrm.main.urls')),
    (r'^system/help$', 'main.views.help'),
    #static content path (js, css...)
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root':settings.MEDIA_ROOT}),
                      
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/(.*)', admin.site.root),
    (r'^i18n/', include('django.conf.urls.i18n')),

)

ahrm/main/models.py
################################################################### #
# Project:    A*HRM                                                 #
# Title:     Class Models of A*HRM Database (PostgrSQL)             #  
# Version:     0001                                                 #
# Last-Modified:     2009-02-26 05:36:39  (Thu, 26 Feb 2009)        #
# Author:     Sokha, Sin , Sanya, Mesa ,Kanel (ALLWEB DEVELOPERS)   #
# Status:     Active                                                #
# Type:     Process                                                 #
# Created:     20-Feb-2009                                          #
# Post-History:     03-Feb-2009                                     #
#####################################################################

from django.db import models
from django.contrib.auth.models import User
from django import forms as forms
from django.forms.widgets import *
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import datetime, time
from tinymce import models as tinymce_models
from django.utils.translation import ugettext_lazy



class Country(models.Model):
    code = models.CharField(max_length=3)
    name = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    language = models.CharField(max_length=100)
    def __unicode__(self):
        return self.name
   
class Gender(models.Model):
    code = models.CharField(max_length=1, primary_key=True)
    desc = models.CharField(max_length=10)
    def __unicode__(self):
        return self.desc

class Company(models.Model):
    desc = models.CharField(ugettext_lazy('Description'),max_length=255)
    name = models.CharField(ugettext_lazy('Name'),max_length=40, )
    address = models.CharField(ugettext_lazy('Address'),max_length=500)
    city = models.CharField(ugettext_lazy('City'),max_length=100, blank=True, null=True)
    zipcode = models.CharField(ugettext_lazy('Zip code'),max_length=5, blank=True, null=True)
    phone1 = models.CharField(ugettext_lazy('Phone1'),max_length=20, blank=True, null=True)
    phone2 = models.CharField(ugettext_lazy('Phone2'),max_length=20, blank=True, null=True)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=40, blank=True, null=True)
    welcome_message = tinymce_models.HTMLField(blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name=ugettext_lazy('Country'))
    logo = models.ImageField(upload_to="images/company_logo/", blank=True, help_text="Should be 50px wide")
    banner = models.ImageField(upload_to="images/company_banner/", blank=True, null=True)
    def __unicode__(self):
        return self.name
    
    def get_name(self):
        return self.name

class UserCompany(models.Model):
    company = models.ForeignKey(Company)
    user = models.ForeignKey(User)
    
class ModelType(models.Model):
    type_code = models.CharField(max_length=50, primary_key=True)
    type_desc = models.CharField(max_length=100)
    def __unicode__(self):
        return self.type_desc
        
class Department(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=50)
    desc = models.CharField(ugettext_lazy('Description'),max_length=200)    
    department_father = models.ForeignKey('self', blank=True, null=True)
    company = models.ForeignKey(Company)
    type = models.ForeignKey(ModelType)
    order_id = models.IntegerField()
    def __unicode__(self):        
        return "%s (%s)" % (self.name, self.company)
        

#This indicate the marital status   
class MaritalStatus(models.Model):
    code = models.CharField(max_length=5)
    desc = models.TextField(ugettext_lazy('Description'),max_length=200)    
    def __unicode__(self):        
        return self.desc
    

class Employee(models.Model):
    lname = models.CharField(ugettext_lazy('Last name'),max_length=200)    
    fname = models.CharField(ugettext_lazy('First name'),max_length=200)
    birthday = models.DateField(ugettext_lazy('Birthday'))
    marital_status = models.ForeignKey(MaritalStatus, verbose_name=ugettext_lazy('Marital Status'))
    driver_licence = models.CharField(ugettext_lazy('Driver licence'),max_length=50, blank=True, null=True)
    street = models.CharField(ugettext_lazy('Street'),max_length=50, blank=True, null=True)
    city = models.CharField(ugettext_lazy('City'),max_length=100)
    zip_code = models.CharField(ugettext_lazy('Zip code'),max_length=5)
    phone = models.CharField(ugettext_lazy('Phone'),max_length=20, blank=True)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=40, blank=True)
    date_joined = models.DateField(ugettext_lazy('Date joined'))
    photo = models.ImageField(upload_to="images/photo/", blank=True, help_text="Should be 50px wide")
    active = models.BooleanField(ugettext_lazy('Active'))
    nationality = models.ForeignKey(Country)
    gender = models.ForeignKey(Gender, verbose_name=ugettext_lazy('Gender'))
    #department = models.ForeignKey(Department, blank=True, null=True)
    company = models.ForeignKey(Company, blank=False, null=False)
    def __unicode__(self):
        return "%s (%s)" % (self.lname, self.fname)
    def get_fullname(self):
       
        return ('%s %s' % (self.fname.upper(),self.lname))        
    get_fullname.short_description = 'Fullname'
    
    def photo_thumb(self):
        if self.photo:
            return '<img src="/%s/%s"></a>' % (settings.MEDIA_ROOT,self.photo)
        return None
    
    def get_age(self):
        current_date = time.localtime()
        birth_date = self.birthday.timetuple()
        
        d_year = current_date[0] - birth_date[0]
        d_month = current_date[1] - birth_date[1]
        d_day = current_date[2] - birth_date[2]
        
        if d_day <0:
            d_day = d_day + 30
            d_month = d_month-1
        #checks if difference in month is negative when difference in day is positive
        if d_month < 0 :
            d_month = d_month + 12
            d_year =  d_year - 1
        #the age found is:  d_year years and d_month months and d_day days
        return d_year
    def first_department_position(self):
        emp_pos = EmployeePosition.objects.filter(employee=self.id)
        if len(emp_pos) >0 :
            return emp_pos[0] 
        else :
            return ""
    photo_thumb.allow_tags = True
    photo_thumb.short_description = 'photo(95px*130px)'
   

class Emergency(models.Model):
    lname = models.CharField(ugettext_lazy('Last name'),max_length=100)    
    fname = models.CharField(ugettext_lazy('First name'),max_length=100)
    phone = models.CharField(ugettext_lazy('Phone'),max_length=50)
    mail = models.EmailField(ugettext_lazy('E-mail'),max_length=50)
    relationship = models.CharField(ugettext_lazy('Relationship'),max_length=50)
    employee = models.ForeignKey(Employee)#A employee has many Emergencies
    
class Experience(models.Model):
    start_date = models.CharField(ugettext_lazy('Start date'),max_length=100,blank=True, null=True)
    end_date = models.CharField(ugettext_lazy('End date'),max_length=100,blank=True, null=True)
    position = models.CharField(ugettext_lazy('Position'),max_length=100, blank=False, null=False)
    mission = models.TextField(ugettext_lazy('Mission'),max_length=1000)
    location = models.CharField(ugettext_lazy('Location'),max_length=100)
    employee = models.ForeignKey(Employee)
    
class Education(models.Model):
    school = models.CharField(ugettext_lazy('School'),max_length=100)
    start_date = models.CharField(ugettext_lazy('End date'),max_length=100,blank=True, null=True)
    end_date = models.CharField(ugettext_lazy('Start date'),max_length=100,blank=True, null=True)
    specialist = models.CharField(ugettext_lazy('Specialist'),max_length=100)
    employee = models.ForeignKey(Employee)
    description = models.TextField(ugettext_lazy('Description'),max_length=1000)

class Skill(models.Model):
    skill_name = models.CharField(ugettext_lazy('Skill'),max_length=100)
    description = models.TextField(max_length=1000, blank=True, null=True)
    employee = models.ForeignKey(Employee)
    
class EmployeeLanguage(models.Model):
    employee = models.ForeignKey(Employee)
    language = models.ForeignKey(Country, verbose_name=ugettext_lazy('Language'))
    COMPETENCY_CHOICES = (('Poor', 'Poor'), ('Basic', 'Basic'), ('Good', 'Good'), ('Mother tongue', 'Mother tongue'))
    FLUENCY_CHOICES = (('Writing' ,'Writing'),('Speaking', 'Speaking'), ('Reading', 'Reading'))
    competency = models.CharField(ugettext_lazy('Competency'),max_length=1, choices=COMPETENCY_CHOICES)
    fluency = models.CharField(ugettext_lazy('Fluency'),max_length=1, choices=FLUENCY_CHOICES)
    def __unicode__(self):
        return self.language


class Position(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=100)
    description = models.CharField(ugettext_lazy('Description'),max_length=500)
    company = models.ForeignKey(Company, blank=False, null=False)
    def __unicode__(self):
        return self.name


class EmployeePosition(models.Model):
    employee = models.ForeignKey(Employee)
    position = models.ForeignKey(Position)
    department = models.ForeignKey(Department, blank=True, null=True)
    def __unicode__(self):
        return str(self.position) + ' - ' + str(self.department) 

class Attachment(models.Model):
    name = models.CharField(ugettext_lazy('Name'),max_length=50)
    description = models.CharField(ugettext_lazy('Description'),max_length=100)
    extension = models.CharField(max_length=10,blank=True, null=True)
    size = models.FloatField(blank=True, null=True)
    content = models.FileField(ugettext_lazy('Content'),upload_to='attachments')
    employee = models.ForeignKey(Employee)
    def get_file_name(self):
        return str(self.content)[len('attachments')+1:]
    
    def get_extension(self):
        str_content=str(self.content)
        return str_content[str_content.find('.'):]

ahrm/templates/about_ahrm.html
{% load i18n %}
<html>
    <head>
        <title>About Allweb Human Resource Management</title>
        <link rel="stylesheet" type="text/css" media="screen" href="/site_media/style.css" />
    </head>
    <body style="background-color: #C1EEFF">
        <table width="100%">
			<tr>
			   <td><img src="/site_media/images/allwelogo.png" width="150" height="150" alt="Human Resource Management" /></td>
			</tr>
			<tr>
			   <td><font color="#E792A0"> <h2>ALLWEB Human Resource Management</h2></font></td>
			</tr>
			<tr>
                <td><font color="gray"> Version 1.02</td>
			</tr>
		</table>
		<br/>
		<table width="100%">
		   <tr>
		       <td>
		           <p align="justify">
		               {% trans 'ALLWEB Human Resource Management is a new system which was created by an open source developers team of ALLWEB  Company.' %}
			           {% trans 'The goal of this system is to provide facilities of company,  department, and employee management for every user at every level.' %} 
			           {% trans 'We provide the functionality that support daily activities at department of human resources.' %}
		           </p><br/>
		           <p align="justify">
		               {% trans 'ALLWEB Human Resource Management is really suitable for small and mid-size business which its daily activities are not much complicated or sophisticated.' %}
		               {% trans 'However, we are  sure that it can extend for giant business because of our well structure organization of this software.' %}
		           </p><br/>
		           <p align="justify">
		               {% trans 'Created  by open source technologies, AHRM is the powerful software that is not only for end user but also for other developers to add more functionalities for their needs.' %}
		               {% trans 'Python with Django framework are the main technologies that we decide to use to build this web system.' %} 
		           </p>
		       </td>
		   </tr>
		</table>
    </body>
</html>

ahrm/templates/companies_list.html
{% extends "master.html" %}
{% load ahrm_tags %}

{% block title %}AHRM - Companies List{% endblock %}

{% block content %}
<h2>Companies List</h2>

{% if companies_list %}
<ul>
  {% for company in companies_list %}
  <li>
    {{company.name}} - {{company.country.name}}
    <ul>
      {{company.department_structure|unordered_list|make_department_links|safe}}
    </ul>
  </li>
  {% endfor %}
</ul>
{% else %}
<p>No companies available</p>
{% endif %}
{% endblock %}

ahrm/templates/companystructure.html
<!--
 ____________________________________________________________
|                                                            |
|    DESIGN + Employee  { Display Employee list }            |
|      DATE + 2009.02.27                                     |
| COPYRIGHT + allweb company                                 |
|____________________________________________________________|

-->
{% extends 'master.html' %}
{% load i18n %}

{% block content %}<!-- 
<link rel="stylesheet" href="/site_media/javascripts/resources/css/ext-all.css" type="text/css" />
<script src="/site_media/javascripts/ext-base.js" type="text/javascript" language="javascript"></script>
<script src="/site_media/javascripts/ext-all.js" type="text/javascript"  language="javascript"></script>  -->  
<script>
//------------------------------------------------Initialize EXTJS --------------------------------------//
	var windowForm;
	var form;
    var tree;
    Ext.onReady(function(){     
        Ext.QuickTips.init();      
      	createTree();      	    	
    });   
    

//----------------------------------------------- Create Tree of Company Structure ----------------------//
    function createTree()
    {     
	    var Tree = Ext.tree;    
	    var tree = new Tree.TreePanel({
	        el:'tree-div',
	        useArrows:true,
	        autoScroll:true,
	        animate:true,
	        enableDD:true,
	        containerScroll: true, 
	        loader: new Tree.TreeLoader({
	            dataUrl:'/treedata/{{ id }}/'
	        })
	        
	    });
	
	    // set the root node
	    var root = new Tree.AsyncTreeNode({
	        text: '{{ name }} Company',
	        draggable:false,
	        id:'company@@@{{ id }}'
	    });
	    	    
	    // Action when drag and drop node of tree
	    tree.on("movenode", function(tree,node,oldParent,newParent,number) {	    		   
			arr_old = oldParent.id.split("@@@");
			arr_new = newParent.id.split("@@@");
			arr_node = node.id.split("@@@");		
			var req = Ext.Ajax.request(
	      	{
		   		method: 'POST',
		   		url: '/movenode/',
		   		params: {number: number, depOldType: arr_old[0], depOldId: arr_old[1],depNewType: arr_new[0], depNewId: arr_new[1],depNodeId: arr_node[1]},	   
		   		failure:function(response, options)
		   		{
		       		alert('not ' + response.text);
			    }
	       	}       	
	       	);
		 });	    
		
		
		
	    tree.setRootNode(root);	    
	    // render the tree
	    tree.render();	    
	    root.expand();	    	    
	    tree.getSelectionModel().on({'click' : function(sm, node){
	    if(node){    		
      		alert("Hello")
       	}
    	},
    	scope:this
    	});
	    tree.getSelectionModel().on({'selectionchange' : function(sm, node){
    	if(node){    		
      		lnkselect(node);
       	}
    	},
    	scope:this
    	});    	
   	}
   	function lnkselect(node){   	       	   
		arr_data = node.id.split("@@@");		
		var req = Ext.Ajax.request(
       	{
	   		method: 'POST',
	   		url: '/viewdetail/',
	   		params: {objType: arr_data[0], objId: arr_data[1]},	   
	   		failure:function(response, options)
	   		{
	       		alert('not ' + response.text);
		    },
		    success: test
       	}       	
       	);      
	}	
	function test(response,options) {
	    document.getElementById("detail_data").innerHTML = response.responseText;
	    //alert(response.responseText);
	}
	function beforeDelete(){
		return confirm("{% trans 'Are you sure to delete this department?' %}");
	}
</script>           
<table>
<tr>
	<td><div id="tree-div" style="overflow:auto; height:300px; width:250px; border:1px solid #c3daf9;"></div></td>		
	<td valign="top"><div id="detail_data"></div></td>
</tr>
</table>
{% endblock %}
{% block footer %}
<center> 
  <a href="http://www.allweb.com.kh">ALLWEB </a> © 2004-2009 Allweb
</center>
{% endblock %}

ahrm/templates/display_department.html
{% extends "master.html" %}

{% block title %}Department {{department.name}}{% endblock %}

{% block content %}
<h2>Department {{department.name}}</h2>
<ul>
  {% for employee in department.employee_set.all %}
  <li>
    {{employee.name}} - <a href="/employee/delete/{{employee.id}}">delete</a>
  </li>
  {% endfor %}
</ul>
<a href="/employee/create_in_dept/{{department.id}}">Create a new employee in this department</a>
{% endblock %}

ahrm/templates/help.html
{% extends 'master.html' %}
{% block content %}

Allweb Human Resource Management System (AHRM)
<p>Human Resource Information System (HRIS),
HR Technology or also called HR modules, refers to the systems and processes at the intersection between human resource management (HRM) and information technology.
It merges HRM as a discipline and in particular its basic HR activities and processes with the information technology field, whereas the programming of data processing systems evolved into standardised routines and packages of enterprise resource planning (ERP) software. 
On the whole, these ERP systems have their origin on software that integrates information from different applications into one universal database. The linkage of its financial and human resource modules through one database is the most important distinction to the individually and proprietary developed predecessors, 
which makes this software application both rigid and flexible.

{% endblock %}

ahrm/templates/login_template.html
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <title>AHRM - Login</title>
    <link rel="stylesheet" type="text/css" media="screen" href="/site_media/style.css" />
    <script type="text/javascript">
       function select_language(language_cd) {
           document.i18n_form.language.value = language_cd;
           document.i18n_form.submit();
       }
    </script>
    {% load i18n %}
<head>
<body>
   <div class="main_div" align="center">
	<div id="header">
       <div id="banner"></div>
    </div>
    <div id="page-wrap">
       <table width="100%" cellpadding="0" cellspacing="0"><tr>
        <td id="main-sidebar" style="background-color: #C1EEFF"></td>
        <td id="main-content">
              <br/>
              <form action="/i18n/setlang/" method="post" name="i18n_form">
                <input name="next" type="hidden" value="" />
                <input type="hidden" name="language" value="" />
                {% for lang in LANGUAGES %}
                   <a href="#" onclick="select_language('{{lang.0}}')" title="{% trans lang.1 %}"><img src="/site_media/images/flags/{{lang.0}}.gif" border="0"/></a>
                   &nbsp;
                {% endfor %}
                
            </form>
			<form method="post" action="/login/verification"><br>
				<table border="0" cellpadding="0" cellspacing="0" width="95%">
				   <tr>
				   	<td style="background-image: url('/site_media/images/left.jpg'); background-repeat: no-repeat;">&nbsp;</td>
				   	<td style="background-image: url('/site_media/images/middle.jpg'); background-repeat: repeat-x" align="center">
				   		<table border=0 width="100%">
				   			<tr>
				    			<td align="center" >
									<table cellpadding="1" cellspacing="1" border="0" align="center" width="75%">
										<tr>
											<td colspan="2" align="center">	
									    		<font style="font-family: serif, cursive;" color="blue" size="5px">
									    		
									    		</font> <br><br>
									    	</td>
										</tr>
									    <tr>
									    	<td width="30%" valign="top" >												
												<img src="/site_media/images/security.jpg"/>
											</td>
										    <td align="right" width="70%" valign="top">										    	{% if login_failed %}
												   <font color="red"><b>
												    {{login_failed}}
												   </b></font>
												    <br/>
												{% endif%}
										    	<table border="1">
										    		<tr>
										    			<td>
										    				<table border="0">
													          <tr>
													             <td width="10%">&nbsp;<td>
													             <td width="40%">&nbsp;<td>
													             <td width="50%">&nbsp;<td>
													          </tr>
													          <tr>
													             <td>&nbsp;<td>
													             <td>{% trans 'User' %}: <td>
													             <td><input type="text" value="{{user_name}}" name="user_name"><td>
													          </tr>
													          <tr>
													             <td>&nbsp;<td>
													             <td>{% trans 'Password' %}: <td>
													             <td><input type="password" value="" name="user_pwd"><td>
													          </tr>
													          <tr>
													             <td>&nbsp;<td>
													             <td>&nbsp;<td>
													             <td>&nbsp;<td>
													          </tr>
													       </table>
										    			</td>
										    		</tr>
										    	</table>
										    	<div style="height: 13px"></div>
										    	<input type="submit" value="{% trans 'Login' %}" style="width: 80px" />
										    </td>
									    </tr>
									</table>
								</td>
							</tr>
							<tr>
								<td>&nbsp;</td>
							</tr>
				   		</table>
				   	</td>
			   		<td width="10px" style="background-image: url('/site_media/images/right.jpg'); background-repeat: repeat-x"></td>						
				   </tr>
				</table>
			</form>
        </td>
        </tr>
        </table>
    </div>
    <div id="footer" align="center">
         <hr/>
         <a href="http://www.allweb.com.kh">Copyright © 2009 Allweb Company.</a>
    </div>
   </div>
</body>
</html>

ahrm/templates/main_page.html
{% extends "master.html" %}
{% load ahrm_tags %}

{% block title %}AHRM - Main Page{% endblock %}

{% block content %}
{% load i18n %}
<br />
<table width="100%" align="center">
    <tr>
        <td>
              {% if company.banner %}
                  <img src="/site_media/{{company.banner}}" width="704" height="170" alt="Human Resource Management" />
              {% else %}
                  <img src="/site_media/images/hr.jpg" width="704" height="170" alt="Human Resource Management" />
              {% endif %}
        </td>       
    </tr>
    <tr>
       <td>
       
            {% if company.welcome_message %}
                  {% autoescape off %}
                      {{company.welcome_message}}
                  {% endautoescape%}
              {% endif %}
       
       </td>
    </tr>
	</table>
  <p>{% trans 'If you have any feedback from our software, please kindly contact us by the following address'%}:</p>
    <table width="100%">
    <tr>
    <td width="70px">
    </td>
    <td>
	<ul>
	  <li>{% trans 'Address' %} : Nº254, {% trans 'IOC Building' %}, {% trans 'Monivong Blvd'%}, {% trans 'Phnom Penh' %}, {% trans 'Cambodia' %}</li>	  
	  <li>{% trans 'Tel' %}     : +(855) 23 221 320</li>
	  <li>{% trans 'E-mail' %}   : <a href="mailto:exalog@allweb.com.kh">exalog@allweb.com.kh</a> </li>
	  <li>{% trans 'Website' %} : <a href="http://www.allweb.com.kh">www.allweb.com.kh</a> </li>	  
	</ul>
	</td>
	</tr>	
	</table>
<br/>
{% endblock %}

ahrm/templates/master.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
{% load i18n %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />    
    <title>{% block title %}Human resource management{% endblock %}</title>
    
    <link rel="stylesheet" type="text/css" media="screen" href="/site_media/style.css" />
    <script src="/site_media/javascripts/ahrm.js" type="text/javascript" language="javascript"></script>
    <link rel="stylesheet" href="/site_media/javascripts/resources/css/ext-all.css" type="text/css" /> 
    <script src="/site_media/javascripts/ext-base.js" type="text/javascript" language="javascript"></script>
    <script src="/site_media/javascripts/ext-all.js" type="text/javascript"  language="javascript"></script>
    <script src="/site_media/javascripts/about_ahrm.js" type="text/javascript"  language="javascript"></script>
    <script src="/site_media/javascripts/about_ahrm_value.js" type="text/javascript"  language="javascript"></script>
    
    <!--[if lt IE 7]>
        <script src="http://ie7-js.googlecode.com/svn/version/2.0(beta3)/IE7.js" type="text/javascript"></script>
    <![endif]-->
    <script type="text/javascript">
       function select_language(language_cd) {
           document.i18n_form.language.value = language_cd;
           document.i18n_form.submit();
       }
    </script>
</head>

<body>
    <div id="header">
       <div id="banner"></div>
    </div>
	<div id="info">
	    <hr/>
		<table width="100%"><tr>
		   <td width="50%">
		      {% ifnotequal company_id 0 %}
		       {{company_name}}
		          {% ifnotequal multi_companies 0 %} 
		          , <a href="/company/change">{% trans 'Change Company' %}</a>
		          {% endifnotequal %}
		      {% endifnotequal %}
		   </td>
		   <td width="50%" align="right">{% trans 'Welcome' %} {{username}}, <a href="/user/changpwd">{% trans 'Change Password' %}</a> / <a href="/logout">{% trans 'Logout' %}</a>
		   </td>
		</tr></table> 
		<hr />
	</div>
    <div id="page-wrap">
        <table width="100%" cellpadding="0" cellspacing="0"><tr valign="top">
        <td id="main-sidebar" style="background-color: #C1EEFF">
           <br/>
           {% ifnotequal company_id 0 %}
            <a href="/mainpage">{% trans 'Main page' %}</a><br/>
            <a href="/company/structure">{% trans 'Company Structure' %}</a><br/>
            <a href="/position">{% trans 'Positions' %}</a><br/>
            <a href="/employee/search">{% trans 'Employees' %}</a><br/>
            <a href="/employee/contactlist">{% trans 'Contacts List' %}</a><br/>
            <a href="#" id="show-btn">{% trans 'About AHRM' %}</a><br/><br/> 
            {% ifequal user_type 0 %}
                   <hr/>
                   <a href="/companies/list">{% trans 'Companies' %}</a><br>
                   <a href="/users/list">{% trans 'Users' %}</a><br/><br/>
            {% else %}
                {% ifequal user_type 2%}
                    <hr/>
                   <a href="/companies/list">Companies</a><br>
                   <a href="/users/list">Users</a><br/><br/>
                {% endifequal %}
            {% endifequal %}
           {% endifnotequal %}
        </td>
        <!-- About Ahrm -->
        <div id="about_ahrm">
            <div id="about_ahrm_data"/>
        </div>
        <!-- End of about ahrm -->
        <td id="main-content" >
        <form action="/i18n/setlang/" method="post" name="i18n_form">
			<input name="next" type="hidden" value="" />
			<input type="hidden" name="language" value="" />
			{% for lang in LANGUAGES %}
			   <a href="#" onclick="select_language('{{lang.0}}')" title="{% trans lang.1 %}"><img src="/site_media/images/flags/{{lang.0}}.gif" /></a>
			   &nbsp;
			{% endfor %}
			
        </form>
        
        
          {% block content %}
                    Here goes the content
          {% endblock %}
        </td>
        </tr></table>
    </div>
    
    <div id="footer" align="center">
         <hr/>
         <a href="http://www.allweb.com.kh">Copyright © 2009 Allweb Company.</a>
    </div>
    
</body>

</html>

ahrm/templates/treedata.html
{% block content %}
{% if jsondata %}
{% autoescape off %}
{{ jsondata }}	
{% endautoescape %}
{% else %}
   <h2>We are updating data!Please Come back later!</h2>   
{% endif %}	
{% endblock %}